name: Build and Push Docker Image

# Trigger this workflow when code is pushed to the 'main' branch
on:
  push:
    branches: [ main ]

# Define the job that will run
jobs:
  build_and_push:
    # Use a fresh Ubuntu Linux runner
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Your Docker Hub username
          username: rhmyee 
          # Use the secret token we created
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Extract the image tag (uses the run number as the version)
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rhmyee/dsp-processor

      # Step 4: Build and Push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
